### ISSUE TITLE
Division of the Y-axis is wrong

### ISSUE THREAD

**Issue by ngreve** [Ho-Ro/openhantek#7] opened 2019-04-18 19:00 UTC
V/div are not equal to the selected settings.
![Screenshot from 2019-04-18 20-55-41](https://user-images.githubusercontent.com/18660100/56384535-e5788d00-621c-11e9-8e4e-3eb00bad1c8c.png)

**Comment by Ho-Ro** [comment] 2019-04-19 19:14
It looks like you measure the calibration output. Please describe your measurement setup, do you use a simple wire connection or one of the provided probes? In the second case, is the probe set to x1 or x10? 
If the wrong scaling is not caused by your probe set to 10x then please check also for different voltage settings, especially 100/200/500 mV.
Rationale: 6022BE and 6022BL hardware differ in setting the voltage gain and I do not own a 6022BL to double check but I got the feedback from at least two 6022BL users that my custom firmware https://github.com/Ho-Ro/Hantek6022API works correctly.

**Comment by Ho-Ro** [comment] 2019-04-22 15:59
Unfortunately no answer to my question above since days - looks like you measured with a probe set to x10. So I'm closing this issue. 
@ngreve Please reopen in case it is really an issue with the firmware or the openhantek program.

**Closed as completed by Ho-Ro** 2019-04-22 15:59 UTC
Labels: question
